spring:
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: my-group

kafka:
  topic:
    name: kafkaTopic

server:
  port: 8082